### ISSUE TITLE
Need documentation about proper caching headers

### ISSUE THREAD

**Issue by patrakov** [novnc/noVNC#1097]
**Describe the bug**

Due to too-aggressive caching in modern browsers, it is impossible to update existing noVNC installations without the users who have connected in the past bumping into the error screen.

**To Reproduce**
1. Install Apache2 on Ubuntu 16.04 or 18.04. Let it serve some domain, e.g. http://novnc.example.com/
2. Add the following lines into the default virtual host:

```
                Alias /noVNC /path/to/noVNC

                <Directory /path/to/noVNC>
                    Require all granted
                </Directory>
```
3. In /path/to/noVNC, have a git checkout of noVNC
4. Checkout revision 5585443 (yes I know, very old)
5. Go to http://novnc.example.com/noVNC/vnc.html?1 using Chromium (tested on version 67.0.3396.87) from a different machine. No need to connect to the VNC screen, just load the page.
6. Checkout revision f90c2a6
7. Go to http://novnc.example.com/noVNC/vnc.html?2 using Chromium
8. See the error
9. Press Ctrl+F5, and the error is gone.

(instead of ?1 and ?2 there were actually paths with different websockify tokens)

**Expected behavior**
No error

**Screenshots**

noVNC encountered an error:

Uncaught ReferenceError: Util is not defined
http://novnc.example.com/noVNC/app/ui.js:62:5
ReferenceError: Util is not defined
    at http://novnc.example.com/noVNC/app/ui.js:62:5
    at http://novnc.example.com/noVNC/app/ui.js:1688:3

**Client (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Browser version: 67

**Server (please complete the following information):**
 - noVNC version: see git commit IDs above
 - VNC server: not relevant
 - WebSocket proxy: not relevant

**Additional context**
The bug happens because the browser loads only vnc.html (due to a query string being different from what has been used before), but skips refreshing the javascripts. The web server has to be configured to prevent this (and the required configuration mentioned in the docs), but I don't really know how to do it properly, so no pull request.

I understand that we cannot change the past and thus cannot fix the error completely. However, something has to be done so that it does not reappear in the future.

And, I would be somewhat more happy if the error dialog contained something like this text, in order to help users:

```
A common cause of errors is browser cache.
Try pressing Ctrl+F5 to bypass it.
```

**Comment by patrakov** [comment]
https://blog.chromium.org/2017/01/reload-reloaded-faster-and-leaner-page_26.html might be a relevant reading

**Comment by patrakov** [comment]
It is important that the bug reproduction should be tried via http (or https with a valid certificate) on a domain name, and not on localhost.

**Comment by patrakov** [comment]
It appears that the following Apache directive, when placed in a Directory block, fixes the Chromium issue:

```
FileETag None
```

Should we distribute the .htaccess file with it?

**Comment by CendioOssman** [comment]
I don't think disabling ETag is a reliable method and just happens to work because of Chromium's current cache policy.

Right now I think `no-cache` is the only directive that will work reliably (assuming the browsers follow the spec). If we want to avoid the validation though it seems like revving is the only method that exists. Maybe we can get `use_require.js` to do something clever for us?

**Comment by DirectXMan12** [comment]
Yeah, I think this is mainly a case of "configuring correct cache headers on your browser".  I don't think `use_require.js` could do anything, because it's a serving issue.  At most, we could probably make `launch.sh` deal with it, but that wouldn't help people serving their own code.  Does serving content with normal modification etags not help?

**Comment by patrakov** [comment]
The issue affects Apache in its default configuration, that's why it has been raised. And, please read the link that I have sent - mere presence of an ETag and no expiration-related headers means "cache forever, do not try to revalidate" for Chrome

**Comment by CendioOssman** [comment]
I don't think we can get optimal cache behaviour if we just treat it as a serving issue. The only way that would work is to force the browser to verify every file every time. And that's what `no-cache` does.

If we want to avoid that verification then we need to describe the relationship between the files. Headers cannot currently do that, so it would have to be in the files.

**Comment by DirectXMan12** [comment]
> If we want to avoid the validation though it seems like revving is the only method that exists. Maybe we can get use_require.js to do something clever for us?

Just to clarify (it's been a while since I've dealt with caching policy and workarounds), are you suggesting the "add a different version to the end of the path" hack?  It's possible my cache tricks knowledge is out of date, but following the FB link, it seems like that's what they suggest ("eeew, that's what etags were supposed to solve" is kinda my response to that, but that's another story).

> The issue affects Apache in its default configuration, that's why it has been raised. 

Sure, but I'd argue that's a general web admin's problem, not a novnc problem, and a web admin can certainly add in a transpilation step to make noVNC files get served at hashed URLs, or they can set short `max-age`, or `no-cache`.  Unless I'm missing something, I feel like this shouldn't be on us as noVNC developers.

**Comment by DirectXMan12** [comment]
> I am asking only for documenting the issue in some README file together with an example Apache configuration snippet.

Ah, ok.  Docs are fine with me :-).
