### ISSUE TITLE
Uncaught RangeError: Source is too large

### ISSUE THREAD

**Issue by lgw8186** [novnc/noVNC#1154]
**Describe the bug**

Windows Server 2008 + UltraVnc + novnc

**To Reproduce**
1. Click on 'link',  can login in  and can display screen
2 After wait 5-10 seconds,  
3. See this error

Uncaught RangeError: Source is too large
http://xx:9000/core/util/cursor.js:104:22
RangeError: Source is too large
    at Uint8ClampedArray.set (<anonymous>)
    at Cursor.change (http://xx:9000/core/util/cursor.js:104:22)
    at RFB._handleCursor (http://xx:9000/core/rfb.js:1541:22)
    at RFB._handleRect (http://xx:9000/core/rfb.js:1501:29)
    at RFB._framebufferUpdate (http://xx:9000/core/rfb.js:1481:23)
    at RFB._normal_msg (http://xx:9000/core/rfb.js:1397:28)
    at RFB._handle_message (http://xx:9000/core/rfb.js:700:31)
    at Websock._recv_message (http://xx:9000/core/websock.js:287:33)

**Screenshots**
![image](https://user-images.githubusercontent.com/14970166/47056016-f5230480-d1ec-11e8-8837-78914e601b55.png)

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce this. What browser are you using? And have you done anything special with the mouse cursor on the server?

**Comment by CendioOssman** [comment]
I checked the code and I don't see how this is possible. That crash indicates that the cursor pixel array is the wrong size. Have you modified the noVNC code in any way?

Can you provide a video of how you produce this? I'm afraid I don't see a way forward without being able to reproduce this.

**Comment by samhed** [comment]
No response.
