### ISSUE TITLE
Issue with launch.sh

### ISSUE THREAD

**Issue by hamidp555** [novnc/noVNC#1499]
running utils/launch.sh returns the following error: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "websockify/__init__.py", line 1, in <module>
    from websockify.websocket import *
  File "websockify/websocket.py", line 25, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by CendioOssman** [comment]
I'm afraid Python 2 support was just removed. What system are you on that is not on Python 3?
