### ISSUE TITLE
Firefox can’t establish a connection to the server at ws://raspberrypi:6080/websockify.

### ISSUE THREAD

**Issue by nn9dev** [novnc/noVNC#1504]
I have noVNC up and running with 

```
pi@raspberrypi:~/gits/noVNC $ ./utils/launch.sh --vnc localhost:5902
Warning: could not find self.pem
Using local websockify at /home/pi/gits/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /home/pi/gits/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5902


Navigate to this URL:

    http://raspberrypi:6080/vnc.html?host=raspberrypi&port=6080

Press Ctrl-C to exit
```

x11vnc is running a server on port 5902. 

```
222/12/2020 16:55:41 WARNING: You are running x11vnc WITHOUT a password.  See
22/12/2020 16:55:41 WARNING: the warning message printed above for more info.
22/12/2020 16:55:41 

The VNC desktop is:      raspberrypi:2
PORT=5902

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching


22/12/2020 16:55:41 check_xrandr_event():
22/12/2020 16:55:41 Detected XRANDR event at location 'check_xevents':
22/12/2020 16:55:41 check_xrandr_event: no change detected.
22/12/2020 16:55:41 check_xrandr_event: enabling full XRANDR trapping anyway.

```

vncserver by realvnc is also running a virtual desktop that x11vnc is reading from (this may be my hitch)

```
pi@raspberrypi:~ $ vncserver
VNC(R) Server 6.7.2 (r42622) ARMv6 (May 13 2020 19:34:20)
Copyright (C) 2002-2020 RealVNC Ltd.
RealVNC and VNC are trademarks of RealVNC Ltd and are protected by trademark
registrations and/or pending trademark applications in the European Union,
United States of America and other jurisdictions.
Protected by UK patent 2481870; US patent 8760366; EU patent 2652951.
See https://www.realvnc.com for information on VNC.
For third party acknowledgements see:
https://www.realvnc.com/docs/6/foss.html
OS: Raspbian GNU/Linux 10, Linux 5.4.79, armv7l

Generating private key... done
On some distributions (in particular Red Hat), you may get a better experience
by running vncserver-virtual in conjunction with the system Xorg server, rather
than the old version built-in to Xvnc. More desktop environments and
applications will likely be compatible. For more information on this alternative
implementation, please see: https://www.realvnc.com/doclink/kb-546

Running applications in /etc/vnc/xstartup

VNC Server catchphrase: "[there is a catchphrase here.]"
             signature: [there is a signature here]

Log file is /home/pi/.vnc/raspberrypi:1.log
New desktop is raspberrypi:1 (192.168.1.37:1)
```

browser console spits out this

```
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
vnc.html
Use of Mutation Events is deprecated. Use MutationObserver instead. handler.js:73:22
Firefox can’t establish a connection to the server at ws://raspberrypi:6080/websockify. websock.js:182:26
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
vnc.html
Use of Mutation Events is deprecated. Use MutationObserver instead. handler.js:73:22
>> RFB.constructor rfb.js:176:13
>> Display.constructor display.js:26:13
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:83.0) Gecko/20100101 Firefox/83.0 display.js:56:13
<< Display.constructor display.js:58:13
<< RFB.constructor rfb.js:285:13
New state 'connecting', was ''. rfb.js:757:13
>> RFB.connect rfb.js:502:13
connecting to ws://raspberrypi:6080/websockify rfb.js:504:13
<< RFB.connect rfb.js:551:13
>> WebSock.onerror: [object Event] websock.js:201:17
WebSocket on-error event rfb.js:279:41
<< WebSock.onerror: [object Event] websock.js:203:17
>> WebSock.onclose websock.js:196:17
WebSocket on-close event rfb.js:246:17
Failed when connecting: Connection closed (code: 1006) rfb.js:808:21
New state 'disconnecting', was 'connecting'. rfb.js:757:13
Firefox can’t establish a connection to the server at ws://raspberrypi:6080/websockify. websock.js:182:26
>> RFB.disconnect rfb.js:555:13
>> Keyboard.allKeysUp keyboard.js:240:13
<< Keyboard.allKeysUp keyboard.js:244:13
<< RFB.disconnect rfb.js:584:13
New state 'disconnected', was 'disconnecting'. rfb.js:757:13
Clearing disconnect timer rfb.js:760:17
<< WebSock.onclose websock.js:198:17
>> Keyboard.allKeysUp keyboard.js:240:13
<< Keyboard.allKeysUp keyboard.js:244:13
>> Keyboard.allKeysUp keyboard.js:240:13
<< Keyboard.allKeysUp keyboard.js:244:13
>> Keyboard.allKeysUp keyboard.js:240:13
<< Keyboard.allKeysUp keyboard.js:244:13
>> Keyboard.allKeysUp keyboard.js:240:13
<< Keyboard.allKeysUp keyboard.js:244:13
>> Keyboard.allKeysUp keyboard.js:240:13
<< Keyboard.allKeysUp keyboard.js:244:13
```

frankly i'm not sure what's wrong here. if anyone could help, i'm happy to provide more info to diagnose the problem. i suspect my odd routing of opening vncserver and then x11vnc is my culprit, but decided i'd post anyways, because i cant figure how to get it to function without doing that.

**Comment by nn9dev** [comment]
I VERY much suspect realvnc/vncserver to be the culprit here, but I decided I'd ask anyways

**Comment by CendioOssman** [comment]
I'm not so sure as things seem to fail very early. I'm assuming you are loading the noVNC page using the same websockify server as you are using for a WebSocket proxy? So there shouldn't be any firewall issues.

Do you get any log lines from websockify when connecting?

And could you try using Firefox' network debugging tool so we can see exactly what happens to the WebSocket connection?

**Comment by nn9dev** [comment]
The window I have ssh'd into my pi didn't spit out anything when trying to connect. Here's a .har file (that's what it made me export it as) from the network debug tool, as well as another log from the console with a bit more info.
[12-23-2020-noVNC_logs-1.zip](https://github.com/novnc/noVNC/files/5736522/12-23-2020-noVNC_logs-1.zip)

**Comment by CendioOssman** [comment]
Unfortunately it included no more information about why it failed to connect. :/

The only thing I notice is that everything else loads using `raspberrypi.local`, but the WebSocket connection has just `raspberrypi`. Other than that I'm afraid you'll have to report this issue to Firefox. We can't really do anything from our end when the browser fails like this.
