### ISSUE TITLE
vnc.html crashes when running inside an <iframe> and "third-party cookies" are blocked

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#1577]
**Describe the bug**
When blocking "third-party cookies" and trying to use vnc.html inside an <iframe> it will try to use `window.localStorage` to read or save settings. This causes a crash and an error message saying:

```
noVNC encountered an error:

Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Module.readSetting (http://samuel:6080/app/webutil.js:159:9)
    at Object.initSetting (http://samuel:6080/app/ui.js:731:27)
    at Object.initSettings (http://samuel:6080/app/ui.js:150:12)
    at Object.start (http://samuel:6080/app/ui.js:59:12)
    at http://samuel:6080/app/ui.js:47:27
```

**To Reproduce**
1. Create a html page with an iframe pointing to your noVNC:
```
<html>
    <body>
        <iframe style="width: 1200px; height: 800px;" src="http://myhost:6080/vnc.html"></iframe>
    </body>
</html>
```
2. Start Incognito-mode in Google Chrome
3. Surf to your html page with the iframe
4. Try to connect
5. See error

**Expected behavior**
noVNC should not crash even if the user changes the default settings in their browser or runs noVNC inside an <iframe> in incognito mode.

**Screenshots**
![third-party-cookie-crash](https://user-images.githubusercontent.com/4117162/132701204-844a30f7-d016-41cc-a603-fdd7b4c67b0e.png)

**Client (please complete the following information):**
 - OS: Fedora 34
 - Browser: Google Chrome
 - Browser version: 92

**Server (please complete the following information):**
 - noVNC version: 1.3.0-beta
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Additional context**
It's most important to not crash in this case, and perhaps log a warning saying we can't read or write settings to localStorage, but we should also investigate if we could work around this issue somehow and still be able to use localStorage.

**Comment by duckduckstab1** [comment]
Maybe the beta's causing it?

**Comment by samhed** [comment]
Same issue exists with v1.2.0, this is not a regression.

**Comment by duckduckstab1** [comment]
Then maybe try 1.1.9?

**Comment by samhed** [comment]
We have noticed this issue in normal use cases, that did not involve iframes, on two of our devices.

We saw it in Edge on Windows 10, and in Safari on iPadOS 15.7. The common denominator here were some modified settings, `Allow sites to save and read cookie data (recommended)` was disabled in Edge, and `Block All Cookies` was enabled in Safari.

While we didn't have more time for testing right now, it is fair to assume that this can happen in more normal circumstances on all platforms and browsers. Our code needs to handle this.
