### ISSUE TITLE
vnc.html crashing on Chrome 57.0.2987.133 (64-bit)

### ISSUE THREAD

**Issue by arcifius** [novnc/noVNC#830]
Cant open the html file... Getting the following from console:

```javascript
browser-es-module-loader.js:1307 Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///C:/Users/1513%20IRON/Documents/noVNC-master/vendor/browser-es-module-loader/dist/babel-worker.js' cannot be accessed from origin 'null'.
    at WorkerPool (file:///C:/Users/1513%20IRON/Documents/noVNC-master/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1307:16)
    at file:///C:/Users/1513%20IRON/Documents/noVNC-master/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1367:19
    at isBrowser (file:///C:/Users/1513%20IRON/Documents/noVNC-master/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:4:34)
    at file:///C:/Users/1513%20IRON/Documents/noVNC-master/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:5:2
browser-es-module-loader.js:1222 Uncaught TypeError: Cannot read property 'import' of undefined
    at ready (browser-es-module-loader.js:1222)
```

**Comment by samhed** [comment]
Can't reproduce in Chrome 58 or 59, did not test 57. What platform are you running Chrome on?

**Comment by CendioOssman** [comment]
I'm afraid it is not possible to run noVNC directly from disk. You have to serve it via a web server. Unfortunately we don't include anything that works on Windows, so you'll have to set up some server yourself.
