### ISSUE TITLE
Hide/remove the port using with noVNC

### ISSUE THREAD

**Issue by rbfigueira** [novnc/noVNC#862]
Hi,
Can anyone tell me the best way to hide/remove the port using with noVNC:

example: http://www.hostname.com:6080/vnc.html?host= www.hostname.com&port=6080
I want using one subdomain (novnc) like : http://novnc.hostname.com/vnc.html?host= www.hostname.com&port=6080

What I really want is to hide/remove the port number from url.
How to do it?

Many thanks

**Comment by samhed** [comment]
use the default port (80 for http and 443 for https)

**Comment by samhed** [comment]
just to clarify; using the default port will allow you to omit the port number from the url

**Comment by rbfigueira** [comment]
Hi,

I have made:
bash ./launch.sh --vnc localhost:80 --listen 443

readlink: illegal option -- f
usage: readlink [-n] [file ...]
Using local websockify at /Library/Server/Web/Data/Sites/www.wrksrv.com/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 443
WebSocket server settings:
  - Listen on :443
  - Web server. Web root: /Library/Server/Web/Data/Sites/www.wrksrv.com/noVNC
  - SSL/TLS support

Traceback (most recent call last):
  File "/Library/Server/Web/Data/Sites/www.wrksrv.com/noVNC/utils/websockify/run", line 5, in <module>
    websockify.websocketproxy.websockify_init()
  File "/Library/Server/Web/Data/Sites/www.wrksrv.com/noVNC/utils/websockify/websockify/websocketproxy.py", line 535, in websockify_init
    server.start_server()
  File "/Library/Server/Web/Data/Sites/www.wrksrv.com/noVNC/utils/websockify/websockify/websockifyserver.py", line 677, in start_server
    tcp_keepintvl=self.tcp_keepintvl)
  File "/Library/Server/Web/Data/Sites/www.wrksrv.com/noVNC/utils/websockify/websockify/websockifyserver.py", line 453, in socket
    sock.bind(addrs[0][4])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
Failed to start WebSockets proxy

In this case I think the port 443 is already in use.
What to do ?

Many thanks

**Comment by samhed** [comment]
You stop the program that is currently using the port. To find the program you could for example use:

    netstat -tulpn

**Comment by kanaka** [comment]
@rbfigueira the parameter "--vnc localhost:80" means that your VNC server is running on port 80 which is pretty unlikely unless you have manually started it that way. Usually VNC server run at 5900 + server number.
