### ISSUE TITLE
Trouble with OS X VNC

### ISSUE THREAD

**Issue by halmos** [novnc/noVNC#918]
Pointed to here from https://github.com/novnc/websockify/issues/301#issuecomment-334750104
Originally thought this was a websockify issue,  @CendioOssman suggested it is noVNC related.

Launching noVNC with `./utils/launch.sh --vnc localhost:5900`

Firefox console reports `WebSocket on-close event` after entering password

and the following error is reported in terminal :
`handler exception: [Errno 57] Socket is not connected`

Has anyone had success working with OSX's system VNC or have tested recommendations for alternative VNC on mac?

**Comment by CendioOssman** [comment]
The server in macOS isn't proper VNC, so the issue might be there. Are you able to connect using other VNC clients?

I can connect fine using noVNC to a macOS machine here, so it does work in some cases at least.

**Comment by halmos** [comment]
I've tried realVNC's VNCServer without luck either. What mac VNC server have you had success with?

My results with RealVNC server 
launching with `./utils/launch.sh --vnc localhost:5900`
console reports:
```
Warning: could not find self.pem
Using local websockify at /Users/e/Documents/librarystack/VM/noVNC/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /Users/e/Documents/librarystack/VM/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900

Navigate to this URL:

    http://e-MBP:6080/vnc.html?host=e-MBP&port=6080

Press Ctrl-C to exit

192.168.2.48: ignoring socket not ready
192.168.2.48: ignoring socket not ready
192.168.2.48: ignoring socket not ready
48.2.168.192.in-addr.arpa - - [09/Oct/2017 11:39:32] 192.168.2.48: Plain non-SSL (ws://) WebSocket connection
48.2.168.192.in-addr.arpa - - [09/Oct/2017 11:39:32] 192.168.2.48: Path: '/websockify'
48.2.168.192.in-addr.arpa - - [09/Oct/2017 11:39:32] connecting to: localhost:5900
handler exception: [Errno 61] Connection refused
```

When I stop the server I do get a python error (not sure if that indicates some larger problem):

```
^C
Terminating WebSockets proxy (45897)
Traceback (most recent call last):
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/run", line 5, in <module>
Process Process-10:
Process Process-8:
Traceback (most recent call last):
Traceback (most recent call last):
Process Process-9:
Process Process-11:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    websockify.websocketproxy.websockify_init()
Traceback (most recent call last):
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketproxy.py", line 551, in websockify_init
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    server.start_server()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 786, in start_server
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
Process Process-12:
    client = self.do_handshake(startsock, address)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
    client = self.do_handshake(startsock, address)
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
Traceback (most recent call last):
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
Process Process-2:
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-3:
    self.msg("In exit")
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 579, in msg
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.logger.log(logging.INFO, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1229, in log
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
Process Process-7:
    client = self.do_handshake(startsock, address)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
Traceback (most recent call last):
    client = self.do_handshake(startsock, address)
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiproces    client = self.do_handshake(startsock, address)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
    self.handle()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
    self.handle()
    SimpleHTTPRequestHandler.handle(self)
    SimpleHTTPRequestHandler.handle(self)
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
    SimpleHTTPRequestHandler.handle(self)
    SimpleHTTPRequestHandler.handle(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
sing/process.py", line 258, in _bootstrap
Process Process-1:
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.handle()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
    SimpleHTTPRequestHandler.handle(self)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    self._target(*self._args, **self._kwargs)
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self._log(level, msg, args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1283, in _log
    self.handle_one_request()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.handle_one_request()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
    self.handle_one_request()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1257, in makeRecord
    client = self.do_handshake(startsock, address)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
    self.handle_one_request()
    self.run()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    self.handle()
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 243, in __init__
    SimpleHTTPRequestHandler.handle(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    def __init__(self, name, level, pathname, lineno,
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 630, in do_SIGTERM
    self.terminate()
    self.handle()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
    SimpleHTTPRequestHandler.handle(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    data = self._sock.recv(self._rbufsize)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
    client = self.do_handshake(startsock, address)
    self.terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
    raise self.Terminate()
    self.RequestHandlerClass(retsock, address, self)
    data = self._sock.recv(self._rbufsize)
      File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
Terminate
    data = self._sock.recv(self._rbufsize)
    self.run()
raise self.Terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
    self.terminate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
websockify.websockifyserver.Terminate
    self.terminate()
    raise self.Terminate()
    self._target(*self._args, **self._kwargs)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 638, in top_new_client
    raise self.Terminate()
Terminate
Terminate
    client = self.do_handshake(startsock, address)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 568, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 97, in __init__
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    WebSocketRequestHandler.__init__(self, req, addr, server)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 34, in __init__
    self.handle()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
    SimpleHTTPRequestHandler.handle(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle_one_request()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
    self.handle_one_request()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    self.handle()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 296, in handle
    SimpleHTTPRequestHandler.handle(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    data = self._sock.recv(self._rbufsize)
eriks-MBP:noVNC erik$   File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
    data = self._sock.recv(self._rbufsize)
    self.terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
    data = self._sock.recv(self._rbufsize)
    raise self.Terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
    self.terminate()
    self.terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
    raise self.Terminate()
    raise self.Terminate()
Terminate
    self.handle_one_request()
Terminate
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
Terminate
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
    self.terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
    raise self.Terminate()
Terminate
    self.handle_one_request()
    data = self._sock.recv(self._rbufsize)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websocketserver.py", line 46, in handle_one_request
    self.terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
    raise self.Terminate()
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
Terminate
    data = self._sock.recv(self._rbufsize)
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 625, in do_SIGINT
    self.terminate()
  File "/Users/erik/Documents/librarystack/VM/noVNC/websockify/websockify/websockifyserver.py", line 603, in terminate
    raise self.Terminate()
Terminate
```

**Comment by halmos** [comment]
There aren't many options for OSX VNC servers available, but I did make some progress using Vine Server. I am now able connect, but the screen rendering is distorted and interlaced in strange ways. The problem appears in both firefox and chrome. 

If anyone has successfully used NoVNC with any OS X VNC server, I would love to know what the working setup is.

**Comment by CendioOssman** [comment]
I've used Apple's remote desktop server that comes with the OS. I wasn't aware of any other servers for macOS.

> handler exception: [Errno 61] Connection refused

In this case your server isn't running on the expected port. Either reconfigure the server to 5900, or change websockify to proxy to the proper port.

> I am now able connect, but the screen rendering is distorted and interlaced in strange ways.

Does it work with other VNC clients? E.g. TigerVNC?

**Comment by halmos** [comment]
Apparently the screen scambling with Vine is a known issue related to retina displays. The software is long out of date so that is not too surprising. 

RealVNC seems to have restrictions that require subscription for direct connections (Rather than through their 'cloud' service). It would be preferable to find an open source solution for this. 

Could you provide more details about what you did to get NoVNC working with the built-in OSX VNC? Whenever I try to connect, the console reports `handler exception: [Errno 57] Socket is not connected`

**Comment by CendioOssman** [comment]
I just enabled it, set the VNC password and off I went. What does websockify say?

Note though that it is breaks the VNC standard in several ways. E.g. keyboard is messed up. So it's not really usable for anything but really basic stuff.

**Comment by halmos** [comment]
The websockify logs don't offer many clues:
```
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /Users/erik/Documents/librarystack/VM/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900
124.2.168.192.in-addr.arpa - - [10/Oct/2017 10:02:06] 192.168.2.124: Plain non-SSL (ws://) WebSocket connection
124.2.168.192.in-addr.arpa - - [10/Oct/2017 10:02:06] 192.168.2.124: Path: '/websockify'
124.2.168.192.in-addr.arpa - - [10/Oct/2017 10:02:06] connecting to: localhost:5900
handler exception: [Errno 57] Socket is not connected
```
Through in checking the OS X ARD logs (screensharingd), i can see that screensharingd crashes every time I try to connect though noVNC. 

Can I ask what version of OS X you are running?

**Comment by halmos** [comment]
Interesting update: I am working on a MacBook Pro with retina display. When I close the display and work off of external monitor only, everything works! It seems retina displays are not only an issue for Vine. 

Thank you for your assistance on this.

**Comment by CendioOssman** [comment]
Alright, so this seems to be a macOS bug in that case. I'll go ahead and close this issue. Thank you for testing and figuring out what happened.

For reference, I did not have retina mode enabled when testing here.
